<?php

namespace DoctrineProxies\__CG__\Perfumeria\Dominio\Productos;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductoCasaPerfume extends \Perfumeria\Dominio\Productos\ProductoCasaPerfume implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'anioLanzamiento', 'genero', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'familiaOlfativa', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'acordes', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'notas', 'id', 'nombre', 'descripcion', 'fechaAlta', 'imagen', 'diseniador'];
        }

        return ['__isInitialized__', 'anioLanzamiento', 'genero', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'familiaOlfativa', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'acordes', '' . "\0" . 'Perfumeria\\Dominio\\Productos\\ProductoCasaPerfume' . "\0" . 'notas', 'id', 'nombre', 'descripcion', 'fechaAlta', 'imagen', 'diseniador'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProductoCasaPerfume $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDiseniador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiseniador', []);

        return parent::getDiseniador();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnioLanzamiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnioLanzamiento', []);

        return parent::getAnioLanzamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', []);

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function getFamiliaOlfativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamiliaOlfativa', []);

        return parent::getFamiliaOlfativa();
    }

    /**
     * {@inheritDoc}
     */
    public function getAcordes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcordes', []);

        return parent::getAcordes();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotas', []);

        return parent::getNotas();
    }

    /**
     * {@inheritDoc}
     */
    public function agregarAcorde(\Perfumeria\Dominio\Perfumes\Acorde $acorde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarAcorde', [$acorde]);

        return parent::agregarAcorde($acorde);
    }

    /**
     * {@inheritDoc}
     */
    public function agregarNota(\Perfumeria\Dominio\Perfumes\Nota $nota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'agregarNota', [$nota]);

        return parent::agregarNota($nota);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

}
